Repository govapps/mtw-nuxt-components, pull requests merged in 2023-08, with the labels that each got.

#9 Alterado tipagem do modal para typeScript
  components/Modal.vue
Labels: enhancement

#7 Alteração da tipagem do componente dialog para TS
  components/Dialog.vue
Labels: enhancement

#8 Adicionando DIV no file Input
  components/Input.vue
Labels: enhancement

#10 Fix: Removido componente TextArea
  components/TextArea.vue
Labels: bug, fix

#11 fix: Ajuste na prop 'isOpen' do componente dialog para required
  components/Dialog.vue
Labels: fix

#13 Correção da validação do input
  components/Input.vue
Labels: bug, fix
